version: '3.8'

services:
  # MongoDB Service
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  # Node.js/Express Server Service
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/yourdbname?authSource=admin
    volumes:
      - ./server:/app
    command: npm start

  # React Client Service
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/app
    command: npm start

volumes:
  mongo-data: